# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: sre-config-reloader-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-exporter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sre-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ include "sre-exporter.ports.grpc" . }}
      targetPort: {{ include "sre-exporter.ports.grpc" . }}
  type: ClusterIP
