# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.otelCollector.externalSecret.enabled .Values.otelCollector.tls.enabled .Values.otelCollector.tls.caSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sre-destination-ca-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        key: {{ .Values.otelCollector.externalSecret.secretKey.destinationCaCert }}
      secretKey: {{ .Values.otelCollector.tls.caSecret.key }}
  refreshInterval: {{ .Values.otelCollector.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: sre-destination-ca-secret
  target:
    creationPolicy: Owner
    name: {{ .Values.otelCollector.tls.caSecret.name }}
{{- end }}
