# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.otelCollector.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sre-destination-url-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        key: {{ .Values.otelCollector.externalSecret.secretKey.destinationUrl }}
      secretKey: {{ .Values.otelCollector.destination.urlSecretKey }}
  refreshInterval: {{ .Values.otelCollector.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: sre-destination-url-secret
  target:
    creationPolicy: Owner
    name: {{ .Values.otelCollector.destination.secretName }}
{{- end }}
