# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.otelCollector.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sre-basic-auth-secret-password
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        key: {{ .Values.otelCollector.externalSecret.secretKey.password }}
      secretKey: {{ .Values.otelCollector.basicAuth.passwordSecretKey }}
  refreshInterval: {{ .Values.otelCollector.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: sre-basic-auth-secret-password
  target:
    creationPolicy: Owner
    name: {{ .Values.otelCollector.basicAuth.passwordSecretName }}
{{- end }}
