# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.otelCollector.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sre-basic-auth-secret-username
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        key: {{ .Values.otelCollector.externalSecret.secretKey.username }}
      secretKey: {{ .Values.otelCollector.basicAuth.usernameSecretKey }}
  refreshInterval: {{ .Values.otelCollector.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: sre-basic-auth-secret-username
  target:
    creationPolicy: Owner
    name: {{ .Values.otelCollector.basicAuth.usernameSecretName }}
{{- end }}
