# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: sre-otel-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "sre-exporter.labels" . | nindent 4 }}
data:
  otel-secret.yaml: |
    {{- tpl (.Files.Get "files/configs/otel.yaml") . | b64enc | nindent 4 }}
