# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.otelCollector.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecretsApiGroup }}
kind: SecretStore
metadata:
  name: sre-destination-url-secret
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    webhook:
      {{- with .Values.otelCollector.externalSecret }}
      url: "{{ required `A valid providerWebhookUrl is required!` .providerWebhookUrl }}?{{ required `A valid providerWebhookQueryKey is required!` .providerWebhookQueryKey }}={{ required `A valid providerSecretName is required!` .providerSecretName }}"
      result:
        jsonPath: {{ .secretPath }}.{{ .secretKey.destinationUrl }}
      {{- end }}
{{- end }}
