# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.otelCollector.externalSecret.enabled .Values.otelCollector.tls.enabled .Values.otelCollector.tls.caSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sre-destination-ca-secret
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    webhook:
      {{- with .Values.otelCollector.externalSecret }}
      url: "{{ required `A valid providerWebhookUrl is required!` .providerWebhookUrl }}?{{ required `A valid providerWebhookQueryKey is required!` .providerWebhookQueryKey }}={{ required `A valid providerSecretName is required!` .providerSecretName }}"
      result:
        jsonPath: {{ .secretPath }}.{{ .secretKey.destinationCaCert }}
      {{- end }}
{{- end }}
