# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-exporter
  namespace: {{ required "A valid vault namespace is required!" .Values.metricsExporter.vaultNamespace }}
rules:
  - apiGroups: [ "" ]  # "" indicates the core API group
    resources: [ "pods" ]
    verbs: [ "list", "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-exporter
  namespace: {{ required "A valid vault namespace is required!" .Values.metricsExporter.vaultNamespace }}
subjects:
  - kind: ServiceAccount
    name: sre-exporter
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: sre-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-exporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-exporter-configmap
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "" ]  # "" indicates the core API group
    resources: [ "configmaps", "pods" ]
    verbs: [ "get", "patch", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-exporter-configmap
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: sre-exporter
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: sre-exporter-configmap
  apiGroup: rbac.authorization.k8s.io
